// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {IOracleRelayer} from "./IOracleRelayer.sol";

/**
 * @title Wrapped HAI (wHAI)
 * @author AI Developer (Generated by Google)
 * @notice This contract creates wHAI, an ERC20 token that is a wrapper for HAI (a free-floating stablecoin).
 * wHAI aims to maintain a 1:1 peg to the US Dollar. It achieves this by being fully backed by HAI
 * and rebalancing user balances based on the HAI redemptionPrice provided by an oracle.
 * @dev Internal balances are stored in terms of the underlying HAI token. Public-facing balances (wHAI)
 * and the wHAI total supply are calculated on-the-fly using the current redemptionPrice.
 * The core invariant is: wHAI.totalSupply() / redemptionPrice == HAI.balanceOf(address(this)).
 * Inspired by rebalancing wrapper tokens.
 */
contract WrappedHAI is ERC20, Ownable {
    using SafeERC20 for IERC20;

    /**
     * @notice The underlying HAI ERC20 token contract.
     */
    IERC20 public immutable HAI;

    /**
     * @notice The Oracle Relayer contract that provides the HAI redemption price.
     */
    IOracleRelayer public immutable ORACLE_RELAYER;

    /**
     * @notice Precision factor for calculations involving 18-decimal tokens. 1e18.
     */
    uint256 private constant PRECISION_FACTOR = 1e18;

    /**
     * @notice Emitted when a user deposits HAI and receives wHAI.
     * @param user The address of the account that received the wHAI (the `receiver` in the deposit function).
     * @param haiAmount The amount of HAI deposited.
     * @param whaiAmount The amount of wHAI minted.
     */
    event Deposit(address indexed user, uint256 haiAmount, uint256 whaiAmount);

    /**
     * @notice Emitted when HAI is withdrawn from the contract, burning wHAI.
     * @param owner The address whose wHAI (implicitly) and HAI (explicitly) are reduced.
     * @param receiver The address that received the withdrawn HAI.
     * @param haiAmount The amount of HAI withdrawn.
     * @param whaiAmount The amount of wHAI conceptually burned.
     */
    event Withdraw(address indexed owner, address indexed receiver, uint256 haiAmount, uint256 whaiAmount);

    /**
     * @notice Initializes the wHAI contract.
     * @param _haiAddress The address of the HAI ERC20 token contract. Must not be the zero address.
     * @param _oracleRelayerAddress The address of the Oracle Relayer contract. Must not be the zero address.
     */
    constructor(address _haiAddress, address _oracleRelayerAddress)
        ERC20("Wrapped HAI", "wHAI") // Sets token name and symbol
        Ownable(msg.sender)          // Sets the deployer as the initial owner
    {
        if (_haiAddress == address(0)) {
            revert("WrappedHAI: HAI address cannot be zero");
        }
        if (_oracleRelayerAddress == address(0)) {
            revert("WrappedHAI: Oracle Relayer address cannot be zero");
        }
        HAI = IERC20(_haiAddress);
        ORACLE_RELAYER = IOracleRelayer(_oracleRelayerAddress);
    }

    /**
     * @notice Calculates the total supply of wHAI.
     * @dev The total supply is dynamic and depends on the total HAI held by this contract
     * and the current redemption price from the oracle.
     * Formula: wHAI_totalSupply = (HAI.balanceOf(address(this)) * redemptionPrice) / PRECISION_FACTOR.
     * Returns 0 if the contract holds no HAI or if the redemptionPrice is 0.
     * @return The total supply of wHAI (with 18 decimals).
     */
    function totalSupply() public view override returns (uint256) {
        uint256 totalHai = HAI.balanceOf(address(this));
        if (totalHai == 0) {
            return 0; // If no HAI is held, wHAI total supply is 0
        }

        uint256 redemptionPrice = ORACLE_RELAYER.redemptionPrice();
        if (redemptionPrice == 0) {
            // If redemption price is 0, wHAI has no value per HAI.
            return 0;
        }

        // Calculate wHAI total supply
        return (totalHai * redemptionPrice) / PRECISION_FACTOR;
    }

    /**
     * @notice Calculates the wHAI balance of a given account.
     * @dev The balance is dynamic and depends on the user's internal HAI balance (stored in `_balances`)
     * and the current redemption price.
     * Formula: wHAI_balance = (internal_HAI_balance * redemptionPrice) / PRECISION_FACTOR.
     * Returns 0 if the account has no internal HAI balance or if the redemptionPrice is 0.
     * Note: `_balances[account]` stores the underlying HAI amount, not wHAI.
     * @param account The address for which to query the balance.
     * @return The wHAI balance of the account (with 18 decimals).
     */
    function balanceOf(address account) public view override returns (uint256) {
        uint256 haiBalance = _balances[account]; // _balances stores underlying HAI
        if (haiBalance == 0) {
            return 0; // If no internal HAI balance, wHAI balance is 0
        }

        uint256 redemptionPrice = ORACLE_RELAYER.redemptionPrice();
        if (redemptionPrice == 0) {
            // If redemption price is 0, wHAI has no value per HAI for this user's balance.
            return 0;
        }

        // Calculate wHAI balance
        return (haiBalance * redemptionPrice) / PRECISION_FACTOR;
    }

    /**
     * @dev Returns the number of decimals used to get its user representation.
     * For wHAI, this is 18, matching standard DeFi conventions and HAI's assumed decimals.
     * This function is overridden for clarity, though ERC20 constructor also sets it.
     */
    function decimals() public pure override returns (uint8) {
        return 18;
    }

    /**
     * @notice Deposits HAI into the contract and mints wHAI for the receiver.
     * @dev Caller (`msg.sender`) must have approved this contract to spend `haiAmountToDeposit` of their HAI.
     * The amount of wHAI minted is calculated based on `haiAmountToDeposit` and the current `redemptionPrice`.
     * Formula: whaiAmount = (haiAmountToDeposit * redemptionPrice) / PRECISION_FACTOR.
     * Emits a {Deposit} event and a standard ERC20 {Transfer} event (for minting).
     * @param haiAmountToDeposit The amount of HAI to deposit. Must be greater than 0.
     * @param receiver The address that will receive the minted wHAI. Cannot be the zero address.
     * @return whaiAmount The amount of wHAI minted (with 18 decimals).
     */
    function deposit(uint256 haiAmountToDeposit, address receiver) public returns (uint256 whaiAmount) {
        if (haiAmountToDeposit == 0) {
            revert("WrappedHAI: Deposit amount must be > 0");
        }
        if (receiver == address(0)) {
            revert("WrappedHAI: Receiver cannot be zero address");
        }

        // Transfer HAI from sender to this contract
        HAI.safeTransferFrom(msg.sender, address(this), haiAmountToDeposit);

        // Increment internal HAI balance for the receiver
        _balances[receiver] += haiAmountToDeposit;

        uint256 redemptionPrice = ORACLE_RELAYER.redemptionPrice();
        // If redemptionPrice is 0, whaiAmount will be 0. User deposits HAI and effectively gets 0 wHAI.
        // This is consistent with the formula. The transaction proceeds.
        whaiAmount = (haiAmountToDeposit * redemptionPrice) / PRECISION_FACTOR;

        emit Deposit(receiver, haiAmountToDeposit, whaiAmount);
        emit Transfer(address(0), receiver, whaiAmount); // ERC20 mint event

        return whaiAmount;
    }

    /**
     * @notice Withdraws `haiAmountToWithdraw` of HAI from the contract for the `owner`, sending HAI to `receiver`.
     * @dev This function allows `msg.sender` to initiate a withdrawal on behalf of `owner`.
     * If `msg.sender` is not `owner`, `msg.sender` must have sufficient wHAI allowance from `owner`
     * for the calculated `whaiAmount` corresponding to `haiAmountToWithdraw`. This allowance is consumed.
     * The amount of wHAI conceptually burned is calculated: whaiAmount = (haiAmountToWithdraw * redemptionPrice) / PRECISION_FACTOR.
     * Reverts if `redemptionPrice` is 0 or if `whaiAmount` calculates to 0 for a non-zero `haiAmountToWithdraw`.
     * Emits a {Withdraw} event and a standard ERC20 {Transfer} event (for burning).
     * @param haiAmountToWithdraw The amount of underlying HAI to withdraw. Must be greater than 0.
     * @param receiver The address that will receive the withdrawn HAI. Cannot be the zero address.
     * @param owner The address whose internal HAI balance (`_balances[owner]`) will be debited,
     *              and whose wHAI allowance for `msg.sender` will be checked and consumed if applicable. Cannot be the zero address.
     * @return whaiAmount The amount of wHAI conceptually burned (with 18 decimals).
     */
    function withdraw(uint256 haiAmountToWithdraw, address receiver, address owner) public returns (uint256 whaiAmount) {
        if (haiAmountToWithdraw == 0) {
            revert("WrappedHAI: Withdraw amount must be > 0");
        }
        if (receiver == address(0)) {
            revert("WrappedHAI: Receiver cannot be zero address");
        }
        if (owner == address(0)) {
            revert("WrappedHAI: Owner cannot be zero address");
        }

        uint256 redemptionPrice = ORACLE_RELAYER.redemptionPrice();
        // Critical: Cannot withdraw HAI if its wHAI value is undefined (price is zero)
        if (redemptionPrice == 0) {
            revert("WrappedHAI: Redemption price is zero, cannot withdraw HAI");
        }

        // Calculate corresponding wHAI amount to be "burned"
        whaiAmount = (haiAmountToWithdraw * redemptionPrice) / PRECISION_FACTOR;

        // Prevent withdrawing HAI for an effective zero wHAI amount due to truncation or extremely low price
        if (whaiAmount == 0 && haiAmountToWithdraw > 0) {
            revert("WrappedHAI: wHAI amount is zero for non-zero HAI withdrawal; check precision or price");
        }

        if (_balances[owner] < haiAmountToWithdraw) {
            revert("WrappedHAI: Owner has insufficient underlying HAI balance");
        }

        // If msg.sender is not the owner, check and consume allowance for the wHAI amount
        if (owner != msg.sender) {
            uint256 currentAllowance = allowance(owner, msg.sender);
            if (currentAllowance < whaiAmount) {
                revert("WrappedHAI: Withdraw amount exceeds wHAI allowance");
            }
            // _approve will call _spendAllowance internally if using OpenZeppelin's latest versions,
            // or directly update allowance. This reduces spender's allowance.
            _approve(owner, msg.sender, currentAllowance - whaiAmount);
        }

        // Decrease owner's internal HAI balance
        _balances[owner] -= haiAmountToWithdraw;

        // Transfer HAI to the receiver
        HAI.safeTransfer(receiver, haiAmountToWithdraw);

        emit Withdraw(owner, receiver, haiAmountToWithdraw, whaiAmount); // Custom event
        emit Transfer(owner, address(0), whaiAmount); // ERC20 burn event

        return whaiAmount;
    }

    /**
     * @dev Overrides ERC20._transfer to update internal HAI balances based on wHAI amounts.
     * This internal function is called by public `transfer` and `transferFrom`.
     * It converts `whaiAmount` to the equivalent `haiAmount` and adjusts underlying balances.
     * Reverts if `redemptionPrice` is 0 and `whaiAmount` > 0.
     * Emits the standard ERC20 {Transfer} event.
     * @param from The address sending wHAI.
     * @param to The address receiving wHAI.
     * @param whaiAmount The amount of wHAI to transfer.
     */
    function _transfer(address from, address to, uint256 whaiAmount) internal override {
        if (from == address(0)) revert("ERC20: transfer from the zero address");
        if (to == address(0)) revert("ERC20: transfer to the zero address");

        if (whaiAmount == 0) {
            // Standard ERC20 behavior: transfer of 0 amount emits event and does nothing else.
            emit Transfer(from, to, 0);
            return;
        }

        uint256 redemptionPrice = ORACLE_RELAYER.redemptionPrice();
        // Critical: Cannot transfer wHAI if its value in HAI is undefined (price is zero)
        if (redemptionPrice == 0) {
            revert("WrappedHAI: Redemption price is zero, cannot transfer wHAI");
        }

        // Calculate the underlying HAI amount corresponding to the wHAI amount
        uint256 haiAmount = (whaiAmount * PRECISION_FACTOR) / redemptionPrice;

        // Note: If whaiAmount is non-zero but rounds down to zero haiAmount due to high price
        // or low whaiAmount, haiAmount will be 0. _balances[from] will be checked against 0.
        // This means a very small wHAI transfer might not move any underlying HAI,
        // but the wHAI Transfer event is still emitted. This is acceptable.

        if (_balances[from] < haiAmount) {
            revert("WrappedHAI: Transfer amount exceeds underlying HAI balance for sender");
        }

        // Adjust internal HAI balances
        _balances[from] -= haiAmount;
        _balances[to] += haiAmount;

        emit Transfer(from, to, whaiAmount);
    }

    // Functions like approve, transferFrom, allowance, increaseAllowance, decreaseAllowance
    // will use OpenZeppelin's ERC20 implementations.
    // - `approve` directly manipulates the `_allowances` mapping for wHAI amounts.
    // - `allowance` reads from the `_allowances` mapping for wHAI amounts.
    // - `transferFrom` first checks allowance (wHAI amount), then calls our overridden `_transfer`
    //   with the wHAI amount, which correctly handles the underlying HAI conversion.
    // - `increaseAllowance` and `decreaseAllowance` also work on wHAI amounts in `_allowances`.
    // No further overrides are needed for these based on the problem description.
}
